config/routes.rb
Rails.application.routes.draw do
  root 'store#index',  as: 'store_index'
  
  # constraints(-> (req) { !req.env['HTTP_USER_AGENT'].include?("Firefox") }) do
  constraints(-> (req) { req.env['HTTP_USER_AGENT'].include?("Firefox") }) do
    get 'admin' => 'admin#index'
    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end
    get 'sessions/create'
    get 'sessions/destroy'

    resources :users do
      collection do
        get :orders
        get :line_items
      end
    end
    resources :products, path: :books do
      get :who_bought, on: :member, format: 'atom'
      get :rate, on: :member
    end
    
    resources :support_requests, only: [ :index, :update]

    scope '(:locale)' do
      resources :orders
      resources :line_items
      resources :carts
      get 'my-orders', to: 'users#orders'
      get 'my-items', to: 'users#line_items'
      get 'categories/:id', to: 'store#index', constraints: { id: /\D.+/ }
      # root 'store#index',  as: 'store_index'
    end

    namespace :admin do
      resources :reports, only: :index
      resources :categories, only: [:index, :show]
    end

    resources :categories do
      resources :products, path: :books
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= yield :head %>
    <title>Depot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript">
      I18n.defaultLocale = "<%= I18n.default_locale %>";
      I18n.locale        = "<%= I18n.locale %>";
    </script>
  </head>

  <body>
    <header class="main">
      <aside>
        <%= form_tag store_index_path, class: 'locale', method: :get do %>
          <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()' %>
          <%= submit_tag 'submit', id: "submit_locale_change" %>
         <p> x-responded-in <%= headers["X-Responded-In"] %> </p>
        <% end %>
      </aside>
      <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf' %>
      <h1><%= @page_title %></h1>
    </header>
    <section class="content">
      <nav class="side_nav">
      <% if @cart %>
      <div id="cart" class="carts">
        <%= render_if @cart && @cart.line_items.any?, @cart %>
      </div>
      <% end %>
        <ul>
          <li><a href="/"><%= t('.home') %></a></li>
          <li><a href="/questions"><%= t('.questions') %></a></li>
          <li><a href="/news"><%= t('.news') %></a></li>
          <li><a href="/contact"><%= t('.contact') %></a></li>
        </ul>
        
        <% if session[:user_id] %>
          <nav class="logged_in_nav">
            <ul>
              <li><%= link_to 'Orders',   orders_path   %></li>
              <li><%= link_to 'Products', products_path %></li>
              <li><%= link_to 'Users',    users_path    %></li>
              <li><%= button_to 'Logout', logout_path, method: :delete   %></li>
            </ul>
          </nav>
        <% end %>
      </nav>
    <main class='<%=controller.controller_name%>'>
      <%= yield %>
    </main>
    </section>  
  </body>
  <%= render file: "layouts/footer" %>
</html>

app/views/layouts/footer.html.erb
<footer>
<p>Count: <%= @page_counter.count %> </p>
<p>Your IP address is: <%= request.remote_ip %></p>
</footer> 

app/views/layouts/myorders.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>